apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: quiz
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: timour259/frontend-jslocal:latest
          env:
            - name: VITE_REACT_APP_API_URL
              value: "http://127.0.0.1:59865/api/questions"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: quiz
spec:
  selector:
    app: frontend
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 30080 # edited
  type: NodePort # nodeport lokal, cluster ip in
