apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: quiz
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
<<<<<<< HEAD
        image: timour259/frontend-jslocal:latest
        env:
        - name: VITE_REACT_APP_API_URL
          value: "http://backend-service.quiz.svc.cluster.local:3000/api/questions"
=======
        image: timour259/frontend-js:latest
        env:
        - name: VITE_REACT_APP_API_URL
          value: "http://timourtest.com/api/questions"
>>>>>>> 46cc5aecfff8d8d40ae9a68c8bd5461e4da93b4f
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: quiz
spec:
  selector:
    app: frontend
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30080  # edited
  type: NodePort  # nodeport lokal, cluster ip in
